version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  build:
    docker:
      - image: nychtelios/meson-build:latest
    steps:
      - checkout
      - restore_cache:
          keys: obj-cache
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init
      - run: apk add paho-mqtt-c
      - run:
          name: Build
          command: meson build -Db_coverage=true --debug --reconfigure
      - run:
          name: Run tests
          command: ninja -C build test
      - save_cache:
          key: obj-cache
          paths:
            - build
            - subprojects
      - run:
          name: Coverage
          command: ninja -C build coverage
      - run: cat build/meson-logs/coverage.txt

workflows:
  mqtt-system-monitor-workflow:
    jobs:
      - build:
          post-steps:
            - codecov/upload:
              file: build/meson-logs/coverage.txt
